apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec: 
  project: default
  source: 
    appURL: https://github.com/argoproj/argocd-example-apps
    path: guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc #cluster URL
    namespace: development
  syncPolicy: #automatically get synched when git repository changed
    automated: 
      prune: true #delete existing resource that are left 
      selfHeal: true #detect drift and update based on git configuration defines
